name: Build API

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Tidy dependencies
        run: go mod tidy
      - name: Build
        run: go build ./cmd/main.go
